:concurrency: 5
:queues:
- default
- metrics
- mailers
- newsletter
- events
- scheduled
- block_user
- reset

:schedule:
  CalculateAllMetrics:
    every: ['24h', first_in: '1m']
    class: CalculateAllMetricsJob
    queue: scheduled
  PreloadOpenData:
    every: ['24h', first_in: '1m']
    class: PreloadOpenDataJob
    queue: scheduled
  OrdersReminder:
    every: ['24h', first_in: '1m']
    class: OrdersReminderJob
    queue: scheduled
  DBReset:
    cron: '0 0 3 * * 1'
    class: DBResetJob
    queue: reset
  DBDump:
    at: '3001/01/01'
    class: DBDumpJob
    queue: reset
